apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/backends: '{"k8s1-42e4f580-kube-system-default-http-backend-80-348ae31c":"HEALTHY","k8s1-42e4f580-reactivemanifest-reactivemanifesto-we-90-f935911d":"HEALTHY"}'
    ingress.kubernetes.io/forwarding-rule: k8s2-fr-dpdfc38p-reactivemanifesto--reactivemanifesto--zzbarglx
    ingress.kubernetes.io/https-forwarding-rule: k8s2-fs-dpdfc38p-reactivemanifesto--reactivemanifesto--zzbarglx
    ingress.kubernetes.io/https-target-proxy: k8s2-ts-dpdfc38p-reactivemanifesto--reactivemanifesto--zzbarglx
    ingress.kubernetes.io/ssl-cert: k8s2-cr-dpdfc38p-wn61qmbplyjui2h0-a4b9eb63829768d0
    ingress.kubernetes.io/static-ip: k8s2-fr-dpdfc38p-reactivemanifesto--reactivemanifesto--zzbarglx
    ingress.kubernetes.io/target-proxy: k8s2-tp-dpdfc38p-reactivemanifesto--reactivemanifesto--zzbarglx
    ingress.kubernetes.io/url-map: k8s2-um-dpdfc38p-reactivemanifesto--reactivemanifesto--zzbarglx
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.class: gce
  creationTimestamp: "2023-10-09T00:33:20Z"
  finalizers:
    - networking.gke.io/ingress-finalizer-V2
  generation: 1
  managedFields:
    - apiVersion: networking.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:kubernetes.io/ingress.allow-http: {}
            f:kubernetes.io/ingress.class: {}
        f:spec:
          f:rules: {}
          f:tls: {}
      manager: GoogleCloudConsole
      operation: Update
      time: "2023-10-09T00:43:18Z"
    - apiVersion: networking.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:ingress.kubernetes.io/backends: {}
            f:ingress.kubernetes.io/forwarding-rule: {}
            f:ingress.kubernetes.io/https-forwarding-rule: {}
            f:ingress.kubernetes.io/https-target-proxy: {}
            f:ingress.kubernetes.io/ssl-cert: {}
            f:ingress.kubernetes.io/static-ip: {}
            f:ingress.kubernetes.io/target-proxy: {}
            f:ingress.kubernetes.io/url-map: {}
          f:finalizers:
            .: {}
            v:"networking.gke.io/ingress-finalizer-V2": {}
        f:status:
          f:loadBalancer:
            f:ingress: {}
      manager: glbc
      operation: Update
      subresource: status
      time: "2023-11-09T18:43:26Z"
  name: reactivemanifesto-ingress
  namespace: reactivemanifesto-website
  resourceVersion: "35776882"
  uid: 2086dc78-067e-46fb-bc6d-9e59bc982fb2
spec:
  rules:
    - host: reactivemanifesto.org
      http:
        paths:
          - backend:
              service:
                name: reactivemanifesto-website-7n7gz
                port:
                  number: 9000
            path: /*
            pathType: ImplementationSpecific
    - host: www.reactivemanifesto.org
      http:
        paths:
          - backend:
              service:
                name: reactivemanifesto-website-7n7gz
                port:
                  number: 9000
            path: /*
            pathType: ImplementationSpecific
  tls:
    - secretName: reactive-manifesto-org-tls-2023-24
status:
  loadBalancer:
    ingress:
      - ip: 34.120.167.124