apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: '{"input":{"containers":[{"limits":{"memory":"1500Mi"},"name":"reactivemanifesto-website"}]},"output":{"containers":[{"limits":{"cpu":"250m","ephemeral-storage":"1Gi","memory":"1500Mi"},"requests":{"cpu":"250m","ephemeral-storage":"1Gi","memory":"1500Mi"},"name":"reactivemanifesto-website"}]},"modified":true}'
    autopilot.gke.io/warden-version: 2.7.41
    deployment.kubernetes.io/revision: "26"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"generation":3,"labels":{"app":"reactivemanifesto-website"},"name":"reactivemanifesto-website","namespace":"reactivemanifesto-website"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"reactivemanifesto-website","deploymentconfig":"reactivemanifesto-website"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"annotations":null,"creationTimestamp":null,"labels":{"app":"reactivemanifesto-website","deploymentconfig":"reactivemanifesto-website"}},"spec":{"containers":[{"env":[{"name":"HTTP_BIND_ADDRESS","value":"0.0.0.0"},{"name":"JAVA_OPTS","value":"-Dpidfile.path=/dev/null -Dconfig.resource=application.conf -Xmx1g -Xms1g -Xss512k -Dfile.encoding=UTF-8"},{"name":"APPLICATION_SECRET","valueFrom":{"secretKeyRef":{"key":"APPLICATION_SECRET","name":"application-secret"}}},{"name":"GITHUB_CLIENT_ID","valueFrom":{"secretKeyRef":{"key":"GITHUB_CLIENT_ID","name":"github-client-id"}}},{"name":"GITHUB_CLIENT_SECRET","valueFrom":{"secretKeyRef":{"key":"GITHUB_CLIENT_SECRET","name":"github-client-secret"}}},{"name":"GOOGLE_API_KEY","valueFrom":{"secretKeyRef":{"key":"GOOGLE_API_KEY","name":"google-api-key"}}},{"name":"GOOGLE_CLIENT_ID","valueFrom":{"secretKeyRef":{"key":"GOOGLE_CLIENT_ID","name":"google-client-id"}}},{"name":"GOOGLE_CLIENT_SECRET","valueFrom":{"secretKeyRef":{"key":"GOOGLE_CLIENT_SECRET","name":"google-client-secret"}}},{"name":"LINKEDIN_CLIENT_ID","valueFrom":{"secretKeyRef":{"key":"LINKEDIN_CLIENT_ID","name":"linkedin-client-id"}}},{"name":"LINKEDIN_CLIENT_SECRET","valueFrom":{"secretKeyRef":{"key":"LINKEDIN_CLIENT_SECRET","name":"linkedin-client-secret"}}},{"name":"MONGODB_URI","valueFrom":{"secretKeyRef":{"key":"MONGODB_URI","name":"mongodb-uri"}}},{"name":"TWITTER_AUTH_KEY","valueFrom":{"secretKeyRef":{"key":"TWITTER_AUTH_KEY","name":"twitter-auth-key"}}},{"name":"TWITTER_AUTH_SECRET","valueFrom":{"secretKeyRef":{"key":"TWITTER_AUTH_SECRET","name":"twitter-auth-secret"}}},{"name":"TWITTER_BEARER_TOKEN","valueFrom":{"secretKeyRef":{"key":"TWITTER_BEARER_TOKEN","name":"twitter-bearer-token"}}}],"image":"docker.cloudsmith.io/generic/reactive:latest","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":9000,"scheme":"HTTP"},"initialDelaySeconds":10,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"name":"reactivemanifesto-website","ports":[{"containerPort":9000,"protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":9000,"scheme":"HTTP"},"initialDelaySeconds":10,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"resources":{"limits":{"memory":"1500Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":0,"conditions":[{"lastTransitionTime":"2020-08-07T13:52:53Z","lastUpdateTime":"2020-08-07T13:52:53Z","message":"Deployment config does not have minimum availability.","status":"False","type":"Available"},{"lastTransitionTime":"2020-08-07T15:21:03Z","lastUpdateTime":"2020-08-07T15:21:03Z","message":"replication controller \"reactivemanifesto-website-1\" is progressing","reason":"ReplicationControllerUpdated","status":"True","type":"Progressing"}],"observedGeneration":3,"replicas":2,"unavailableReplicas":2,"updatedReplicas":2}}
  creationTimestamp: "2023-10-06T22:08:46Z"
  generation: 27
  labels:
    app: reactivemanifesto-website
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
                f:deploymentconfig: {}
            f:spec:
              f:containers:
                k:{"name":"reactivemanifesto-website"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"APPLICATION_SECRET"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                    k:{"name":"GITHUB_CLIENT_ID"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                    k:{"name":"GITHUB_CLIENT_SECRET"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                    k:{"name":"GOOGLE_API_KEY"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                    k:{"name":"GOOGLE_CLIENT_ID"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                    k:{"name":"GOOGLE_CLIENT_SECRET"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                    k:{"name":"HTTP_BIND_ADDRESS"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"JAVA_OPTS"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"LINKEDIN_CLIENT_ID"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                    k:{"name":"LINKEDIN_CLIENT_SECRET"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                    k:{"name":"MONGODB_URI"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                    k:{"name":"TWITTER_AUTH_KEY"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                    k:{"name":"TWITTER_AUTH_SECRET"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                    k:{"name":"TWITTER_BEARER_TOKEN"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                  f:imagePullPolicy: {}
                  f:livenessProbe:
                    .: {}
                    f:failureThreshold: {}
                    f:httpGet:
                      .: {}
                      f:path: {}
                      f:port: {}
                      f:scheme: {}
                    f:initialDelaySeconds: {}
                    f:successThreshold: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":9000,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:protocol: {}
                  f:readinessProbe:
                    .: {}
                    f:failureThreshold: {}
                    f:httpGet:
                      .: {}
                      f:path: {}
                      f:port: {}
                      f:scheme: {}
                    f:initialDelaySeconds: {}
                    f:periodSeconds: {}
                    f:successThreshold: {}
                    f:timeoutSeconds: {}
                  f:resources:
                    .: {}
                    f:limits:
                      .: {}
                      f:memory: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
      manager: kubectl-create
      operation: Update
      time: "2023-10-06T22:08:45Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:kubectl.kubernetes.io/last-applied-configuration: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2023-10-06T22:31:39Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:strategy:
            f:rollingUpdate:
              f:maxSurge: {}
              f:maxUnavailable: {}
          f:template:
            f:spec:
              f:containers:
                k:{"name":"reactivemanifesto-website"}:
                  f:image: {}
                  f:livenessProbe:
                    f:periodSeconds: {}
                    f:timeoutSeconds: {}
              f:imagePullSecrets:
                .: {}
                k:{"name":"cloudsmith-internal-registry"}: {}
      manager: GoogleCloudConsole
      operation: Update
      time: "2023-10-25T03:45:23Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:kubectl.kubernetes.io/restartedAt: {}
      manager: kubectl-rollout
      operation: Update
      time: "2023-11-10T19:26:10Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2023-11-10T19:27:49Z"
  name: reactivemanifesto-website
  namespace: reactivemanifesto-website
  resourceVersion: "36814161"
  uid: 25024f6f-8609-4b0e-a524-dbebbba35227
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: reactivemanifesto-website
      deploymentconfig: reactivemanifesto-website
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-11-10T19:26:10Z"
      creationTimestamp: null
      labels:
        app: reactivemanifesto-website
        deploymentconfig: reactivemanifesto-website
    spec:
      containers:
        - env:
            - name: HTTP_BIND_ADDRESS
              value: 0.0.0.0
            - name: JAVA_OPTS
              value: -Dpidfile.path=/dev/null -Dconfig.resource=application.conf -Xmx1g
                -Xms1g -Xss512k -Dfile.encoding=UTF-8
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  key: APPLICATION_SECRET
                  name: application-secret
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: GITHUB_CLIENT_ID
                  name: github-client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: GITHUB_CLIENT_SECRET
                  name: github-client-secret
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_API_KEY
                  name: google-api-key
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CLIENT_ID
                  name: google-client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CLIENT_SECRET
                  name: google-client-secret
            - name: LINKEDIN_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: LINKEDIN_CLIENT_ID
                  name: linkedin-client-id
            - name: LINKEDIN_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: LINKEDIN_CLIENT_SECRET
                  name: linkedin-client-secret
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: MONGODB_URI
                  name: mongodb-uri
            - name: TWITTER_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  key: TWITTER_AUTH_KEY
                  name: twitter-auth-key
            - name: TWITTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  key: TWITTER_AUTH_SECRET
                  name: twitter-auth-secret
            - name: TWITTER_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  key: TWITTER_BEARER_TOKEN
                  name: twitter-bearer-token
          image: docker.cloudsmith.io/lightbend/internal-registry/reactivemanifesto-website:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 15
          name: reactivemanifesto-website
          ports:
            - containerPort: 9000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 1Gi
              memory: 1500Mi
            requests:
              cpu: 250m
              ephemeral-storage: 1Gi
              memory: 1500Mi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: cloudsmith-internal-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2023-11-10T02:31:04Z"
      lastUpdateTime: "2023-11-10T02:31:04Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2023-10-07T15:35:50Z"
      lastUpdateTime: "2023-11-10T19:27:49Z"
      message: ReplicaSet "reactivemanifesto-website-7f557788f9" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 27
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1